name: Daily Commit

on:
  schedule:
    - cron: "30 2 * * *"  # Runs every day at 02:30 UTC (adjust time as needed)
  workflow_dispatch:  # Allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 21f3000745@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily_update.txt
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "21f3000745@ds.study.iitm.ac.in"
          git add .
          git commit -m "Automated daily commit: $(date)"
          git push
